---
bareos_install_server: true
bareos_setup_db: true
bareos_sensu_postgres_pass: password
bareos_clients:
  - name: client
    address: "{{ hostvars['client'].ansible_default_ipv4.address }}"
    password: client_password
    enable_backup_job: true
